#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 29 08:55:52 2017

@author: wuzhenglung
"""

import flask


class internal_web:
    def __init__(self):
        print('test')
        
        




if __name__=="__main__":
    internal_web()
    
    